version: '3.8'
services:
  postgres:
    image: postgres
    container_name: mypostgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: messagenotification
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: huy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "8080:80"

volumes:
  postgres_data:
